sudo: false

language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - TESTS_ZEND_BARCODE_PDF_SUPPORT: true
    - SITE_URL: https://zendframework.github.io/zend-barcode
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-barcode.git
    - secure: "OcQVNRTNC4jq+z7P2IvpUNB8RBA00wnlQb2NV5cq4yWqHOOS6yFdRttzklJocPJ8U6rrMFRgTSdnEXtJU4kpL1esR7Q5zS28bwogG1sCRGl0FYjmH6bc28pi5ayktiE/s8ycO6Bqg7qcX/uQDy2SbEIiWPk2Pg8YuKHu59lpQbqKHI45qfqALr0LcL6JdY5ktqX8ZuIe1S4Ovmylzir8T3FCKGFMFP86G580/aOhzxoMSlWVsWMhAh9RUVgPCmXxvwWh2s62GU2mPS9HJA6XcESp05pRQbjoifmvcnbrFx+AOMqmAhvlcrnozlwyKCbTLpTgpgDsjltNsEBYfolThHGNbTyZ9LpMGXVgTziVTbr+UqxjwXpBVPjbkpv4f1I3WwjqtJBOs1HIlNEgppug/Zyc6NfvCFL/ayXmQkdDSN7VpiFt88T9cIxw/2rmvSKi/qOtZv9Fhssucg2yufB9xLSWiGQt5+8aMbDUcBfwAuxoCg5C0YO05DQTWkb+ZAj7NOp7gGPWGJwWxY6lT+DKHVx7RcejcOczvxNPmnTPsCGE2EepTzZ+NwPubcoRWjx3DHe/vlU9dOSNGyUiW9ttocUj6eEiZTB2P9IsJ19gT+8dJ88gcSdRiaxNV+2LX+MBe3L4j5YzHzDH4reyPK1NR4m9Lmv1GCoQ04qozaCo0/U="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - CS_CHECK=true
    - php: 5.5
      env:
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: 5.6
      env:
        - TEST_COVERAGE=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: 7
    - php: 7
      env:
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: hhvm 
    - php: hhvm 
      env:
        - SERVICE_MANAGER_VERSION="^2.7.5"
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - if [[ $SERVICE_MANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:$SERVICE_MANAGER_VERSION" ; fi
  - if [[ $SERVICE_MANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:^3.0.3" ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi
